resources:
  repositories:
    - repository: templates
      type: github
      name: dirigeants/pipelines
      endpoint: KlasaCommunityPlugins

jobs:
  - template: lint.yml@templates

  - template: docs.yml@templates
    parameters:
      ghRef: 'github.com/KlasaCommunityPlugins/functions'
      targetBranch: 'docs'
      sync: 'false'
      dependsOn: Lint
